config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :reservations, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :animals, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create] do
      member do
        patch 'accept'
        patch 'decline'
      end
    end
  end
  namespace :owners do
    resources :reservations
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :race, presence: true

  mount_uploader :photo, PhotoUploader

  include PgSearch::Model
  pg_search_scope :search_by_race_and_description,
    against: [ :race, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  require 'date'
  belongs_to :user
  belongs_to :animal


  enum status: [:pending, :validated, :canceled]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals
  has_many :reservations, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, uniqueness: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create, :delete]

  def index
    @animals = Animal.all.order(created_at: :desc)
    if params[:query].present?
      sql_query = "race ILIKE :query OR description ILIKE :query"
      @animals = Animal.where(sql_query, query: "%#{params[:query]}%")
    else
      @animals = Animal.all
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @reservation = Reservation.new
    # authorize @animal

    @localisations = User.geocoded
    @markers = @localisations.map do |localisation|
      {
        lat: localisation.latitude,
        lng: localisation.longitude
      }
    end
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    if @animal.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
  end

  def destroy
    @current_user = Animal.where(user: current_user)
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
    # authorize @animal
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :race, :description, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  #include Pundit

  # after_action :verify_authorized, except: [:index, :new, :create], unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :phone_number
    ])
  end

  private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/owners/reservations_controller.rb
class Owners::ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :destroy]
  # before_action :set_reservation, only: [:index, :accept, :create, :decline, :destroy]

  def index
    @reservations = Reservation.all.order(created_at: :desc)
    # @reservations = Reservation.where(user: current_user)
    @reservations = Animal.where(user: current_user)
    @reservations
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @animals = Animal.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :create, :accept, :decline]
  before_action :set_reservation, only: [:owner_index, :accept, :decline, :destroy]
  def index
    @reservations = Reservation.all.order(created_at: :desc)
  end

  def accept
    @reservation.validated!
    redirect_to reservations_path

    # authorize @reservation
  end

  def decline
    @reservation.destroy
    redirect_to reservations_path

    # authorize @reservation
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.animal = @animal
    @reservation.user_id = current_user[:id]
    # authorize @reservation

    if @reservation.save
      redirect_to reservations_path # notice: "#{@animal.name} a été seléctionné(e)!"
    else
      render "animals/show"
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
    # authorize @reservation
  end

  def reservation_params
    params.require(:reservation).permit(:date, :status, :user_id, :animal_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.erb
<div class="animals-index banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1535907309959-db0f3e78aa54?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
  <div class="container d-flex flex-column align-items-end justify-content-end">
    <h1>Pense Bêtes</h1>
    <p>Un pense bête pas si bête</p>
  </div>
</div>

<br>

<div class="container">
  <div class="form-inline " >
       <!--  <h4>Dates : </h4> -->
        <%= form_tag animals_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control text-center",
            placeholder: "Entrez le nom de l'animal"%>
            <%= submit_tag "Voir la liste", class: "btn btn-home" %>
        <% end %>
      </div><br><br>

  <div class="cards">
    <% @animals.each do |animal| %>
     <div class="card-category"
         style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)),
         url('<%= cl_image_path animal.photo, height: 300, width: 400,  gravity: :face %>')">
        <h3 alt="animal.race"> <%= link_to animal.name , animal_path(animal) %> </h3>
      </div>
    <% end %>
  </div>

</div>

app/views/animals/new.html.erb
<div class="container">
  <%= simple_form_for(@animal) do |f| %>
    <%= f.input :name %>
    <%= f.input :race %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class: "btn btn-rent"%>
  <% end %>
</div>

app/views/animals/show.html.erb
<div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active container-fluid">
                <%= cl_image_tag @animal.photo, crop: :fit%>
            </div>
            <div class="carousel-item">
                <img src="https://images.unsplash.com/photo-1462218503178-e822ff881c43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://grandbaby-cakes.com/wp-content/uploads/2015/06/Balsamic-Brown-Sugar-Lamb-Chops-1.jpg" class="d-block w-100" alt="...">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="description rows d-flex mt-4">
        <div class="colums col-8">
            <h1>
                <%= @animal.name %>
            </h1>
            <br>
            <h3>
                <%= @animal.race %>
            </h3>
            <br>
            <%= @animal.description %>
        </div>
        <div>
          <h3 class="text-secondary">Adresse :</h3>
          <div
            id="map"
            style="width: 400px;
            height: 300px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          </div>
        </div>
    </div>
</div>
<div class="container">
        <div class="form-wrapper ">
            <h3 class="text-secondary">Choisir les dates :</h3>
            <%= simple_form_for [@animal, @reservation] do |t| %>
            <%= t.input :start_date, as: :string, input_html: {id: "start_date"}, label: "Du" %> <br>
            <%= t.input :end_date, as: :string, input_html: {id: "end_date"}, label: "Au" %> <br>
            <%= t.submit "Bêeee", class: "btn btn-rent mr-5" %>
              <% if current_user == @animal.user %>
              <%= link_to "Supprimer", animal_path(@animal), class: "btn btn-danger mr-5",
                                method: :delete,
                                data: { confirm: "Voulez-vous vraiment tuer?" } %>
              <% end %>
              <%= link_to "Retour", animals_path, class: "btn btn-back " %>
            <% end %>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tout Doux</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application'%>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!--  Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer'  %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>


  </body>
</html>

app/views/owners/reservations/index.html.erb
<div class="container">
  <br>
  <h1 class="text-center">Vos animaux</h1>
  <br>
  <div class="cards">
    <% @reservations.each do |reservation| %>

     <div class="card-category"
         style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path reservation.photo%>')">
        <h3> <%= link_to reservation.name, animal_path(reservation) %> </h3>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1484557985045-edf25e08da73?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80);">
  <div class="container">
    <h1>Pense Bêtes</h1>
    <h2>Un pense-bête pas si bête ! </h2><br><br><br>
    <p><strong>Mettez à dispotion</strong> ou <strong>empruntez un animal</strong> pour effectuer des tâches ou activités à <strong> moindre coût </strong>tout en étant <strong>écolo </strong>! <br>
    Un mouton pour tondre votre gazon ? Un cheval pour se balader ? Un canard pour faire du foie gras ? </p> <br>
    <br>
  </div>

 <br><br>

<div class="container">
   <div class="form-wrapper " >
     <!--  <h4>Dates : </h4> -->
      <%= form_tag animals_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Entrez la race de l'animal"%>
      <!--  <% end %> <br> -->
      <%= simple_form_for :search, method: :get do |t| %>
        <%= submit_tag "Voir la liste", class: "btn btn-home mt-4" %>
      <% end %>
   </div>
 </div>
 <br><br><br><br><br>

app/views/reservations/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <!-- [...] -->
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <!-- [...] -->
<% end %>

app/views/reservations/index.html.erb
<div class="animals-index banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1422363119751-1d2b703a7546?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1502&q=80);">
    <div class="container d-flex flex-column align-items-end justify-content-end">
        <h1>Réservations</h1>
    </div>
</div>
<br>
<div class="container">

  <% @reservations.each do |reservation| %>

    <div class="card-container">
      <div class="animal-card my-4">
        <div class="card-category2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path reservation.animal.photo%>')">
        <h2 class="text-center"> <%= link_to "#{reservation.animal.name}", animal_path(reservation.animal) %> </h2>
        </div>

        <br>
        <div class="card-category-infos"/>
        <h5><%= reservation.status %></h5>
          <div class="form-inline">
            <label for="exampleFormControlTextarea1" spaceholder="Leave a message for the owner about your needs"></label>
            <textarea class="" id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>
          <div class="animal-buttons">

            <% if reservation.pending? %>
              <%= link_to "Confirmer", accept_animal_reservation_path(reservation.animal, reservation), method: :patch, class: "btn btn-rent my-3" %>
              <%= link_to "Supprimer", decline_animal_reservation_path(reservation.animal, reservation), method: :patch, class: "btn btn-danger my-3" %>
              <% elsif reservation.validated?%>
              <%= link_to "Supprimer", decline_animal_reservation_path(reservation.animal, reservation), method: :patch, class: "btn btn-danger my-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-drumstick-bite"></i> by us
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "Kawaii_Bull.jpg", class: "avatar" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
          <%= link_to "Mes réservations", reservations_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Mes animaux", owners_reservations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Nouveau", new_animal_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag 'https://st2.depositphotos.com/1007566/12064/v/950/depositphotos_120647154-stock-illustration-cute-goat-animal-tender-isolated.jpg',class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>